version: "3.1"

services:
  backend:
    container_name: task-management-backend
    restart: always
    build: ./
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=user
      - MONGO_PASSWORD=password
      - MONGO_DATABASE=task
      - ACCESS_TOKEN_SECRET=secret
    ports:
      - "3000:3000"
  mongo:
    image: mongo:4.2
    container_name: task-management-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=task
    volumes:
      - mymongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mymongodata:
